USE [DemoLab]
GO
/****** Object:  Table [dbo].[CUSTOMERS]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CUSTOMERS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[CUSTOMERS](
	[CUSTOMER_ID] [int] NOT NULL,
	[CUST_FIRST_NAME] [nvarchar](20) NOT NULL,
	[CUST_LAST_NAME] [nvarchar](20) NOT NULL,
	[NLS_LANGUAGE] [nvarchar](3) NULL,
	[NLS_TERRITORY] [nvarchar](30) NULL,
	[CREDIT_LIMIT] [decimal](9, 2) NULL,
	[CUST_EMAIL] [nvarchar](30) NULL,
	[ACCOUNT_MGR_ID] [int] NULL,
	[DATE_OF_BIRTH] [datetime] NULL,
	[MARITAL_STATUS] [nvarchar](20) NULL,
	[GENDER] [nvarchar](1) NULL,
	[INCOME_LEVEL] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
