USE [DemoLab]
GO
/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[EMPLOYEES](
	[EMPLOYEE_ID] [int] NOT NULL,
	[FIRST_NAME] [nvarchar](20) NULL,
	[LAST_NAME] [nvarchar](25) NOT NULL,
	[EMAIL] [nvarchar](25) NOT NULL,
	[PHONE_NUMBER] [nvarchar](20) NULL,
	[HIRE_DATE] [datetime] NULL,
	[JOB_ID] [nvarchar](10) NULL,
	[SALARY] [decimal](8, 2) NULL,
	[COMMISSION_PCT] [decimal](2, 2) NULL,
	[MANAGER_ID] [int] NULL,
	[DEPARTMENT_ID] [int] NULL,
 CONSTRAINT [EMP_EMP_ID_PK] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [EMP_EMAIL_UK] UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[EMP_DEPT_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES]  WITH CHECK ADD  CONSTRAINT [EMP_DEPT_FK] FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENTS] ([DEPARTMENT_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[EMP_DEPT_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES] CHECK CONSTRAINT [EMP_DEPT_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[EMP_MANAGER_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES]  WITH CHECK ADD  CONSTRAINT [EMP_MANAGER_FK] FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[EMP_MANAGER_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES] CHECK CONSTRAINT [EMP_MANAGER_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[EMP_SALARY_MIN]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES]  WITH CHECK ADD  CONSTRAINT [EMP_SALARY_MIN] CHECK  (([salary]>(0)))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[EMP_SALARY_MIN]') AND parent_object_id = OBJECT_ID(N'[dbo].[EMPLOYEES]'))
ALTER TABLE [dbo].[EMPLOYEES] CHECK CONSTRAINT [EMP_SALARY_MIN]
GO
