USE [DemoLab]
GO
/****** Object:  Table [dbo].[ORDER_ITEMS]    Script Date: 2022/3/19 下午 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ORDER_ITEMS](
	[ORDER_ID] [int] NOT NULL,
	[LINE_ITEM_ID] [int] NOT NULL,
	[PRODUCT_ID] [int] NOT NULL,
	[UNIT_PRICE] [decimal](8, 2) NULL,
	[QUANTITY] [int] NULL,
 CONSTRAINT [ORDER_ITEMS_PK] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC,
	[LINE_ITEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Index [ITEM_ORDER_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]') AND name = N'ITEM_ORDER_IX')
CREATE NONCLUSTERED INDEX [ITEM_ORDER_IX] ON [dbo].[ORDER_ITEMS]
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [ITEM_PRODUCT_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]') AND name = N'ITEM_PRODUCT_IX')
CREATE NONCLUSTERED INDEX [ITEM_PRODUCT_IX] ON [dbo].[ORDER_ITEMS]
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [ORDER_ITEMS_UK]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]') AND name = N'ORDER_ITEMS_UK')
CREATE UNIQUE NONCLUSTERED INDEX [ORDER_ITEMS_UK] ON [dbo].[ORDER_ITEMS]
(
	[ORDER_ID] ASC,
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS_ORDER_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]'))
ALTER TABLE [dbo].[ORDER_ITEMS]  WITH CHECK ADD  CONSTRAINT [ORDER_ITEMS_ORDER_ID_FK] FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDERS] ([ORDER_ID])
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS_ORDER_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]'))
ALTER TABLE [dbo].[ORDER_ITEMS] CHECK CONSTRAINT [ORDER_ITEMS_ORDER_ID_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS_PRODUCT_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]'))
ALTER TABLE [dbo].[ORDER_ITEMS]  WITH CHECK ADD  CONSTRAINT [ORDER_ITEMS_PRODUCT_ID_FK] FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCT_INFORMATION] ([PRODUCT_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS_PRODUCT_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDER_ITEMS]'))
ALTER TABLE [dbo].[ORDER_ITEMS] CHECK CONSTRAINT [ORDER_ITEMS_PRODUCT_ID_FK]
GO
