USE [DemoLab]
GO
/****** Object:  Table [dbo].[DEPARTMENTS]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DEPARTMENTS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[DEPARTMENTS](
	[DEPARTMENT_ID] [int] NOT NULL,
	[DEPARTMENT_NAME] [nvarchar](30) NULL,
	[MANAGER_ID] [int] NULL,
	[LOCATION_ID] [int] NULL,
 CONSTRAINT [DEPT_ID_PK] PRIMARY KEY CLUSTERED 
(
	[DEPARTMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[DEPT_LOC_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[DEPARTMENTS]'))
ALTER TABLE [dbo].[DEPARTMENTS]  WITH CHECK ADD  CONSTRAINT [DEPT_LOC_FK] FOREIGN KEY([LOCATION_ID])
REFERENCES [dbo].[LOCATIONS] ([LOCATION_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[DEPT_LOC_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[DEPARTMENTS]'))
ALTER TABLE [dbo].[DEPARTMENTS] CHECK CONSTRAINT [DEPT_LOC_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[DEPT_MGR_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[DEPARTMENTS]'))
ALTER TABLE [dbo].[DEPARTMENTS]  WITH CHECK ADD  CONSTRAINT [DEPT_MGR_FK] FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[DEPT_MGR_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[DEPARTMENTS]'))
ALTER TABLE [dbo].[DEPARTMENTS] CHECK CONSTRAINT [DEPT_MGR_FK]
GO
