USE [DemoLab]
GO
/****** Object:  Table [dbo].[COUNTRIES]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[COUNTRIES]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[COUNTRIES](
	[COUNTRY_ID] [char](2) NOT NULL,
	[COUNTRY_NAME] [nvarchar](40) NULL,
	[REGION_ID] [int] NULL,
 CONSTRAINT [COUNTRY_C_ID_PK] PRIMARY KEY CLUSTERED 
(
	[COUNTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[COUNTR_REG_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[COUNTRIES]'))
ALTER TABLE [dbo].[COUNTRIES]  WITH CHECK ADD  CONSTRAINT [COUNTR_REG_FK] FOREIGN KEY([REGION_ID])
REFERENCES [dbo].[REGIONS] ([REGION_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[COUNTR_REG_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[COUNTRIES]'))
ALTER TABLE [dbo].[COUNTRIES] CHECK CONSTRAINT [COUNTR_REG_FK]
GO
