USE [DemoLab]
GO
/****** Object:  Table [dbo].[TA]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TA]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TA](
	[C1] [int] NOT NULL,
	[C2] [nvarchar](10) NULL,
 CONSTRAINT [PK_TA] PRIMARY KEY CLUSTERED 
(
	[C1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
