USE [DemoLab]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 2022/3/19 下午 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[ORDERS](
	[ORDER_ID] [int] NOT NULL,
	[ORDER_DATE] [datetime] NULL,
	[ORDER_MODE] [nvarchar](8) NULL,
	[CUSTOMER_ID] [int] NULL,
	[ORDER_STATUS] [int] NULL,
	[ORDER_TOTAL] [decimal](8, 2) NULL,
	[SALES_REP_ID] [int] NULL,
	[PROMOTION_ID] [int] NULL,
 CONSTRAINT [ORDER_PK] PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Index [ORD_CUSTOMER_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS]') AND name = N'ORD_CUSTOMER_IX')
CREATE NONCLUSTERED INDEX [ORD_CUSTOMER_IX] ON [dbo].[ORDERS]
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [ORD_ORDER_DATE_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS]') AND name = N'ORD_ORDER_DATE_IX')
CREATE NONCLUSTERED INDEX [ORD_ORDER_DATE_IX] ON [dbo].[ORDERS]
(
	[ORDER_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [ORD_SALES_REP_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS]') AND name = N'ORD_SALES_REP_IX')
CREATE NONCLUSTERED INDEX [ORD_SALES_REP_IX] ON [dbo].[ORDERS]
(
	[SALES_REP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS_CUSTOMER_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [ORDERS_CUSTOMER_ID_FK] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMERS] ([CUSTOMER_ID])
ON DELETE SET NULL
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS_CUSTOMER_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [ORDERS_CUSTOMER_ID_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS_SALES_REP_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [ORDERS_SALES_REP_FK] FOREIGN KEY([SALES_REP_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
ON DELETE SET NULL
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[ORDERS_SALES_REP_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [ORDERS_SALES_REP_FK]
GO
IF NOT EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_TOTAL_MIN]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS]  WITH CHECK ADD  CONSTRAINT [ORDER_TOTAL_MIN] CHECK  (([order_total]>=(0)))
GO
IF  EXISTS (SELECT * FROM sys.check_constraints WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_TOTAL_MIN]') AND parent_object_id = OBJECT_ID(N'[dbo].[ORDERS]'))
ALTER TABLE [dbo].[ORDERS] CHECK CONSTRAINT [ORDER_TOTAL_MIN]
GO
