USE [DemoLab]
GO
/****** Object:  Table [dbo].[LOCATIONS]    Script Date: 2022/3/19 下午 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[LOCATIONS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[LOCATIONS](
	[LOCATION_ID] [int] NOT NULL,
	[STREET_ADDRESS] [nvarchar](40) NULL,
	[POSTAL_CODE] [nvarchar](12) NULL,
	[CITY] [nvarchar](30) NULL,
	[STATE_PROVINCE] [nvarchar](25) NULL,
	[COUNTRY_ID] [char](2) NULL,
 CONSTRAINT [LOC_ID_PK] PRIMARY KEY CLUSTERED 
(
	[LOCATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [LOC_CITY_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOCATIONS]') AND name = N'LOC_CITY_IX')
CREATE NONCLUSTERED INDEX [LOC_CITY_IX] ON [dbo].[LOCATIONS]
(
	[CITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [LOC_COUNTRY_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOCATIONS]') AND name = N'LOC_COUNTRY_IX')
CREATE NONCLUSTERED INDEX [LOC_COUNTRY_IX] ON [dbo].[LOCATIONS]
(
	[COUNTRY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [LOC_STATE_PROVINCE_IX]    Script Date: 2022/3/19 下午 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[LOCATIONS]') AND name = N'LOC_STATE_PROVINCE_IX')
CREATE NONCLUSTERED INDEX [LOC_STATE_PROVINCE_IX] ON [dbo].[LOCATIONS]
(
	[STATE_PROVINCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[LOC_C_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[LOCATIONS]'))
ALTER TABLE [dbo].[LOCATIONS]  WITH CHECK ADD  CONSTRAINT [LOC_C_ID_FK] FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[COUNTRIES] ([COUNTRY_ID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[LOC_C_ID_FK]') AND parent_object_id = OBJECT_ID(N'[dbo].[LOCATIONS]'))
ALTER TABLE [dbo].[LOCATIONS] CHECK CONSTRAINT [LOC_C_ID_FK]
GO
