USE [DemoLab]
GO
/****** Object:  UserDefinedFunction [dbo].[GET_TAB]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[GET_TAB]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
BEGIN
execute dbo.sp_executesql @statement = N'CREATE FUNCTION [dbo].[GET_TAB] (@DEPARTMENT_ID int) RETURNS TABLE
  AS RETURN (
    SELECT A.EMPLOYEE_ID, A.LAST_NAME, A.SALARY, A.DEPARTMENT_ID, B.DEPARTMENT_NAME
      FROM EMPLOYEES A, DEPARTMENTS B
	 WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
	   AND A.DEPARTMENT_ID = @DEPARTMENT_ID
);
' 
END
GO
