USE [DemoLab]
GO
/****** Object:  Table [dbo].[REGISTRATION]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[REGISTRATION]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[REGISTRATION](
	[st_no] [nvarchar](10) NOT NULL,
	[course_no] [nvarchar](10) NOT NULL,
	[semester] [smallint] NOT NULL,
	[score] [smallint] NULL
) ON [PRIMARY]
END
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_REGISTRATION]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[REGISTRATION]') AND name = N'IX_REGISTRATION')
CREATE NONCLUSTERED INDEX [IX_REGISTRATION] ON [dbo].[REGISTRATION]
(
	[st_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_REGISTRATION_1]    Script Date: 2022/3/19 ¤U¤È 01:44:46 ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[REGISTRATION]') AND name = N'IX_REGISTRATION_1')
CREATE NONCLUSTERED INDEX [IX_REGISTRATION_1] ON [dbo].[REGISTRATION]
(
	[st_no] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGISTRATION_COURSE1]') AND parent_object_id = OBJECT_ID(N'[dbo].[REGISTRATION]'))
ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRATION_COURSE1] FOREIGN KEY([course_no])
REFERENCES [dbo].[COURSE] ([course_no])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGISTRATION_COURSE1]') AND parent_object_id = OBJECT_ID(N'[dbo].[REGISTRATION]'))
ALTER TABLE [dbo].[REGISTRATION] CHECK CONSTRAINT [FK_REGISTRATION_COURSE1]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGISTRATION_STUDENT1]') AND parent_object_id = OBJECT_ID(N'[dbo].[REGISTRATION]'))
ALTER TABLE [dbo].[REGISTRATION]  WITH CHECK ADD  CONSTRAINT [FK_REGISTRATION_STUDENT1] FOREIGN KEY([st_no])
REFERENCES [dbo].[STUDENT] ([st_no])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_REGISTRATION_STUDENT1]') AND parent_object_id = OBJECT_ID(N'[dbo].[REGISTRATION]'))
ALTER TABLE [dbo].[REGISTRATION] CHECK CONSTRAINT [FK_REGISTRATION_STUDENT1]
GO
